spring:

  config:
    import: classpath:application-db.yml

  jpa:

    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
