INSERT INTO FILE_EXTENSION (FILE_EXTENSION_NAME, FILE_EXTENSION_TYPE, FILE_EXTENSION_VISIBILITY) VALUES('bat','FIX', 'HIDE');
INSERT INTO FILE_EXTENSION (FILE_EXTENSION_NAME, FILE_EXTENSION_TYPE, FILE_EXTENSION_VISIBILITY) VALUES('cmd', 'FIX', 'HIDE');
INSERT INTO FILE_EXTENSION (FILE_EXTENSION_NAME, FILE_EXTENSION_TYPE, FILE_EXTENSION_VISIBILITY) VALUES('com', 'FIX', 'HIDE');
INSERT INTO FILE_EXTENSION (FILE_EXTENSION_NAME, FILE_EXTENSION_TYPE, FILE_EXTENSION_VISIBILITY) VALUES('cpl', 'FIX', 'HIDE');
INSERT INTO FILE_EXTENSION (FILE_EXTENSION_NAME, FILE_EXTENSION_TYPE, FILE_EXTENSION_VISIBILITY) VALUES('exe', 'FIX', 'HIDE');
INSERT INTO FILE_EXTENSION (FILE_EXTENSION_NAME, FILE_EXTENSION_TYPE, FILE_EXTENSION_VISIBILITY) VALUES('scr', 'FIX', 'HIDE');
INSERT INTO FILE_EXTENSION (FILE_EXTENSION_NAME, FILE_EXTENSION_TYPE, FILE_EXTENSION_VISIBILITY) VALUES('js', 'FIX', 'HIDE');
